# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
    contents: read
    checks: write
    pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Test Repository
      uses: actions/checkout@v4
      with:
        repository: "emorarescu/OpenApiTestingInGithubActions"
        path: test-project
        ref: "test_PR_2"
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Checkout Development Repository
      uses: actions/checkout@v4
      with:
        repository: "emorarescu/OpenAPI_Stub_Testing"
        ref: "master"
        path: stub-app

#    - name: Set up JDK 17
#      uses: actions/setup-java@v4
#      with:
#        java-version: '17'
#        distribution: 'temurin'
#    - name: Run STUB
#      run: mvn clean install -DskipTests
#    - name: Start Spring Boot application
#      run: |
#        nohup mvn spring-boot:run > app.log 2>&1 &
#        sleep 5

    - name: Build Stub
      working-directory: stub-app
      run: mvn clean install -DskipTests
    - name: Start Stub Application
      working-directory: stub-app
      run: |
        nohup mvn spring-boot:run \
          -Dspring-boot.run.main-class=org.example.Main \
          > app.log 2>&1 &
        echo $! > app.pid
        sleep 6
        cat app.log
    - name: Run tests
      working-directory: test-project
      run: mvn test -Dtags=eugen

    - name: Publish Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Surefire Tests
        path: '**/target/surefire-reports/TEST-*.xml'
        reporter: java-junit
        contents: read
        checks: write
        working-directory: test-project

    - name: Stop Stub Application
      if: always()
      working-directory: stub-app
      run: |
        if [ -f app.pid ]; then kill $(cat app.pid) || true; fi
